export const SET_AUTHED_USER = "SET_AUTHED_USER";
export const RECEIVE_USERS = "RECEIVE_USERS";
export const UPDATE_USER_ANSWER = "UPDATE_USER_ANSWER";
export const UPDATE_USER_QUESTIONS = "UPDATE_USER_QUESTIONS";
export const RECEIVE_QUESTIONS = "RECEIVE_QUESTIONS";
export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const ADD_QUESTION = "ADD_QUESTION";
export const SET_PREVIOUS_PATH = "SET_PREVIOUS_PATH";